@echo off
echo Ejecutando composer update...
call composer update
echo Ejecutando composer install...
call composer install
echo Copiando .env.example a .env...
call copy .env.example .env
echo Generando clave de aplicación...
call php artisan key:generate
